      - - name: Bytebase Login
  # You may pin to the exact commit or the version.
  # uses: bytebase/login-action@3c2d2089d38cad435c7c00892204e7e5c7c4cba1
  uses: bytebase/login-action@v1.0.0
  with:
    # The Bytebase instance URL, should be the Bytebase external URL
    bytebase-url: 
    # Bytebase API version
    api-version: # optional, default is v1
    # The Bytebase service account key
    service-key: 
    # The Bytebase service account secret
    service-secret: 
          
